# Generated by Django 6.0.5 on 2026-06-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evidence_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectevidence',
            options={'ordering': ['category', '-uploaded_at']},
        ),
        migrations.RenameIndex(
            model_name='projectevidence',
            new_name='core_projec_student_5f8090_idx',
            old_name='core_projec_student_8f3a21_idx',
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/'),
        ),
        migrations.AlterField(
            model_name='projectevidence',
            name='category',
            field=models.CharField(choices=[('material_identification', 'Material identification'), ('project_process', 'Project process'), ('final_product', 'Final product')], max_length=40),
        ),
    ]
