# Generated by Django 6.0.5 on 2026-06-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_projectevidence_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='project_title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
