# Generated by Django 6.0.5 on 2026-06-21 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_observation_checklist_format_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPromotionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_academic_year', models.PositiveIntegerField(help_text='Last academic/calendar year learners were in their previous class.')),
                ('to_academic_year', models.PositiveIntegerField()),
                ('promoted_count', models.PositiveIntegerField(default=0)),
                ('graduated_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-from_academic_year'],
            },
        ),
        migrations.AlterModelOptions(
            name='observationcriterion',
            options={'ordering': ['competency__order', 'section_code', 'order', 'id']},
        ),
        migrations.RenameIndex(
            model_name='classprojecttheme',
            new_name='core_classp_school__5a69c5_idx',
            old_name='core_classp_school__a8f2c1_idx',
        ),
        migrations.RenameIndex(
            model_name='cohortprojecttheme',
            new_name='core_cohort_school__cc16a4_idx',
            old_name='core_cohort_school__a8f2c1_idx',
        ),
        migrations.RenameIndex(
            model_name='observationchecklist',
            new_name='core_observ_school__f87fa3_idx',
            old_name='core_observ_school__a8ea0d_idx',
        ),
        migrations.RenameIndex(
            model_name='observationchecklist',
            new_name='core_observ_school__4ac030_idx',
            old_name='core_observ_school__b7e4a2_idx',
        ),
        migrations.RenameIndex(
            model_name='studentobservationrating',
            new_name='core_studen_student_060365_idx',
            old_name='core_studen_student_8f0a21_idx',
        ),
        migrations.AddField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=True, help_text='False when the learner has graduated (e.g. after S6 end-of-year promotion).'),
        ),
        migrations.AddField(
            model_name='student',
            name='graduated_year',
            field=models.PositiveIntegerField(blank=True, help_text='Calendar year when the learner completed S6 and left the active roster.', null=True),
        ),
        migrations.AlterField(
            model_name='observationchecklist',
            name='class_level',
            field=models.CharField(blank=True, choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6')], default='', help_text='Class this checklist applies to (required on upload).', max_length=2),
        ),
        migrations.AlterField(
            model_name='observationchecklist',
            name='year',
            field=models.PositiveIntegerField(help_text='Calendar year when this checklist was uploaded (for reference).'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Platform Superadmin'), ('overall_supervisor', 'Overall Supervisor'), ('supervisor', 'Supervisor')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'active'], name='core_studen_school__236b47_idx'),
        ),
        migrations.AddField(
            model_name='academicpromotionrun',
            name='run_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_promotion_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicpromotionrun',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_runs', to='core.school'),
        ),
        migrations.AddConstraint(
            model_name='academicpromotionrun',
            constraint=models.UniqueConstraint(fields=('school', 'from_academic_year'), name='unique_school_promotion_from_year'),
        ),
    ]
