# Generated by Django 6.0.5 on 2026-08-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_student_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='When True, user must set a new password before using the rest of the app (used for auto-generated one-time supervisor logins).'),
        ),
    ]
