"""UNEB Revised Project Observation Checklist 2026 (cohort 2026+)."""

from __future__ import annotations

from .common import CHECKBOX_MAX_RATING, HEADER_MAX_RATING, ObsItem

CHECKLIST_DOCUMENT = {
    "board": "UGANDA NATIONAL EXAMINATIONS BOARD",
    "title": "REVISED PROJECT OBSERVATION CHECKLIST 2026",
    "instructions_title": "Instructions to the facilitator.",
    "instructions": [
        "This observation checklist contains four competencies which must be assessed from S.3 to S.4.",
        "The period of assessment for each competency is as follows;",
        "Please Tick against the indicator(s) the learner has exhibited at every competence assessed.",
        "Record the Number of Indicators Observed in the box provided at the end of each competence.",
        "Indicate N/A if the learner has not been assessed for a particular competence(s)",
    ],
    "assessment_period_rows": [
        {
            "sn": "1",
            "competency": "Project Planning",
            "period": "S.3 Term 1 to Term 2",
            "submission": "By the last week of 2nd Term holiday of S.3",
        },
        {
            "sn": "2",
            "competency": "Project Implementation",
            "period": "S.3 Term 3 to S.4 Term 1",
            "submission": "By the last week of 1st Term holiday of S.4",
        },
        {
            "sn": "3",
            "competency": "Project Reporting",
            "period": "S.4 Term 2",
            "submission": "By the last week of 2nd Term holiday of S.4",
        },
        {
            "sn": "4",
            "competency": "Project Dissemination",
            "period": "S.4 Term 2",
            "submission": "By the last week of 2nd Term holiday of S.4",
        },
    ],
}

CHECKLIST_COMPETENCY_HEADINGS = {
    "Project planning": "COMPETENCY 1: PROJECT PLANNING",
    "Project implementation": "COMPETENCY 2: PROJECT IMPLEMENTATION",
    "Project reporting": "COMPETENCY 3: PROJECT REPORTING",
    "Project dissemination": "COMPETENCY 4: PROJECT DISSEMINATION",
}

# Subjects in section 1.8 exactly as listed on the official form (two-column layout).
PLANNING_SUBJECTS = [
    "English Language",
    "Literature in English",
    "CRE",
    "IRE",
    "History and Political Education",
    "Geography",
    "Ugandan Sign Language",
    "Chinese",
    "Arabic",
    "Latin",
    "Local Languages",
    "French",
    "German",
    "Mathematics",
    "Physics",
    "Chemistry",
    "Biology",
    "General Science",
    "Performing Arts",
    "Entrepreneurship",
    "Technology and Design",
    "Nutrition and Food Technology",
    "Physical Education",
    "ICT",
    "Agriculture",
    "Art and Design",
]

# (competency_name, section_code, section_title, section_preamble, [observations...])
STRUCTURED_CHECKLIST: list[tuple[str, str, str, str, list[ObsItem]]] = [
    # —— COMPETENCY 1: PROJECT PLANNING (1.1 – 1.10) ——
    (
        "Project planning",
        "1.1",
        "Identifies a Problem",
        "The learner identifies the problem that the project intends to solve by:",
        [
            "Studying the environment of the community to identify a problem.",
            "Reading and reviewing or listening to information in order to identify the problem.",
            "Consulting internal or external community members in order to identify a problem",
            "Writing the problem identified",
        ],
    ),
    (
        "Project planning",
        "1.2",
        "Develops a Project Title",
        "The learner develops a project title that:",
        [
            "Contains the problem to be solved",
            "Is related to the theme",
            "Has the acceptable number of words 7-25.",
        ],
    ),
    (
        "Project planning",
        "1.3",
        "Generates the Purpose of the project",
        "The learner generates the purpose of the project by:",
        [
            "Providing the reason(s) for carrying out the project.",
            "Providing a purpose which reflects the title.",
        ],
    ),
    (
        "Project planning",
        "1.4",
        "Develops Project Objectives",
        "The learner develops project objectives that are:",
        [
            "Specific.",
            "Measurable.",
            "Achievable.",
            "Realistic.",
            "Time bound.",
            "Linked to the purpose.",
        ],
    ),
    (
        "Project planning",
        "1.5",
        "Identifies Resources Needed for the Project",
        "The learner identifies resources needed to carry out the project, He/she:",
        [
            "Identifies the resources needed",
            "Provides justification for the resources identified",
            "Costs the resources identified",
        ],
    ),
    (
        "Project planning",
        "1.6",
        "Identifies the risks",
        "The learner identifies the risks anticipated during the project",
        [
            "Identifies the risks",
            "Provides the actions to take to minimize the risks",
        ],
    ),
    (
        "Project planning",
        "1.7",
        "Develops a Project Activity Plan",
        "The learner develops a project activity plan for carrying out the project. It should include:",
        [
            "Relevant project activities.",
            "Logically sequenced activities.",
            "The periods for carrying out each activity",
            "Responsible persons for carrying out the activities",
        ],
    ),
    (
        "Project planning",
        "1.8",
        "Integrates Knowledge and Skills of Different Subjects",
        "The learner integrates knowledge and skills from different subjects:",
        list(PLANNING_SUBJECTS),
    ),
    (
        "Project planning",
        "1.9",
        "Integrates Cross Cutting Issues",
        "The learner integrates different cross cutting issues in the project:",
        [
            "Environmental awareness.",
            "Health awareness.",
            "Mixed abilities and involvement.",
            "Socio-economic issues.",
            "Citizenship and Patriotism.",
        ],
    ),
    (
        "Project planning",
        "1.10",
        "Demonstrates Generic Skills during the Project Process",
        "The learner demonstrates generic skills during the project process and:",
        [
            ("i) Critical thinking and problem solving", HEADER_MAX_RATING),
            "Plans and carries out critical investigations.",
            "sorts and analyses information.",
            "Identifies problems and ways forward.",
            "Predicts outcomes and makes reasoned decisions.",
            "Evaluates different solutions.",
            ("ii) Communication", HEADER_MAX_RATING),
            "Listens attentively and with comprehension.",
            "Talks confidently and explains ideas/opinions clearly.",
            "Reads accurately and fluently.",
            "Writes and presents coherently.",
            "Uses a range of media to communicate ideas.",
            ("iii) Creativity and innovation", HEADER_MAX_RATING),
            "Uses imaginations to explore possibilities.",
            "Works with others to generate ideas.",
            "Suggests and develops new solutions",
            "Tries out innovative alternatives.",
            "Looks for patterns and makes generalizations.",
            ("iv) Mathematical computation and ICT proficiency", HEADER_MAX_RATING),
            "Uses numbers and measurements accurately.",
            "Interprets and interrogates mathematical data.",
            "Uses mathematics to justify and support decisions.",
            "Uses technology to create, manipulate and process information.",
            "Uses technology to collaborate, communicate and refine their work.",
            ("v) Cooperation and self-directed learning", HEADER_MAX_RATING),
            "Work effectively in diverse teams.",
            "Interact effectively with others.",
            "Takes responsibility for your own learning.",
            "Works independently with persistence",
            "Manages goals and time",
        ],
    ),
    # —— COMPETENCY 2: PROJECT IMPLEMENTATION ——
    (
        "Project implementation",
        "2.1",
        "Obtains Resources Needed for the Project",
        "The learner obtains resources needed for the project through:",
        [
            "Borrowing.",
            "Exchange of materials.",
            "Buying resources.",
            "Improvising.",
            "Fundraising for materials.",
        ],
    ),
    (
        "Project implementation",
        "2.2",
        "Uses the Obtained Resources",
        "The learner uses the obtained resources for:",
        [
            "The planned purpose.",
            "Multiple purposes.",
            "Uses all the gathered resources",
        ],
    ),
    (
        "Project implementation",
        "2.3",
        "Creates a Product/Service",
        "The learner creates a product or service that:",
        [
            "Is in line with the stated objectives.",
            "Is authentic (learners own original work).",
            "Unique (exceptional, extra ordinary).",
        ],
    ),
    # —— COMPETENCY 3: PROJECT REPORTING ——
    (
        "Project reporting",
        "3.1",
        "Uses an Appropriate Report Format",
        "The learner uses an appropriate format to generate a project report that contains:",
        [
            "The title.",
            "The introduction.",
            "The body.",
            "The conclusion.",
        ],
    ),
    (
        "Project reporting",
        "3.2",
        "Develops the introduction for project report",
        "The learner develops the introduction that contains:",
        [
            "The name of the project.",
            "The objectives.",
            "The purpose of the project.",
        ],
    ),
    (
        "Project reporting",
        "3.3",
        "Develops the body for the project report",
        "The learner develops the body that contains:",
        [
            "The project activities carried out.",
            "The achievements.",
            "The resources mobilized and used.",
            "The challenges faced while carrying out the project.",
            "How the challenges faced were solved?",
            "Lessons and skills learnt while carrying out the project.",
        ],
    ),
    (
        "Project reporting",
        "3.4",
        "Develops the conclusion for the project report",
        "The learner presents the conclusion that contains:",
        [
            "An overall evaluation of the project.",
            "Recommendations related to the project.",
        ],
    ),
    (
        "Project reporting",
        "3.5",
        "Uses appropriate language in the project report",
        "The learner uses appropriate language in the project report that contains:",
        [
            "At least 5 terminologies related to the project.",
            "Has less than 5 spelling errors.",
            "Has less than 5 punctuation errors.",
            "Has less than 5 tense errors.",
        ],
    ),
    (
        "Project reporting",
        "3.6",
        "Keeps project records",
        "The learner keeps the following project records:",
        [
            "Project plan.",
            "Budget.",
            "Activity plan.",
            "Stakeholder engagement documents (letters, attendance lists, reports, pictures, recordings, minutes etc.).",
            "Facilitator - learner interaction records.",
            "Project report.",
        ],
    ),
    # —— COMPETENCY 4: PROJECT DISSEMINATION ——
    (
        "Project dissemination",
        "4.1",
        "Disseminates the project through speaking or signing",
        "The learner orally / through signing disseminates the project report:",
        [
            "With logical flow of ideas.",
            "Using appropriate tense / timelines.",
            "Using terminologies related to the project.",
            "Using the aspects of voice /nonverbal cues /signs.",
            "Using appropriate voice projection /signs (speed and thickness).",
            "Pronouncing words correctly/ using appropriate signs.",
            "Using appropriate body language.",
        ],
    ),
    (
        "Project dissemination",
        "4.2",
        "Publishes the project report",
        "The learner publishes the project report /findings through;",
        [
            "School library.",
            "News Papers.",
            "Magazines.",
            "Posters/Bill boards/Notice boards.",
            "Project exhibition.",
        ],
    ),
]

