"""UNEB Continuous Assessment Observation Checklist (cohort 2025)."""

from __future__ import annotations

from .common import HEADER_MAX_RATING, ObsItem

CHECKLIST_DOCUMENT = {
    "board": "UGANDA NATIONAL EXAMINATIONS BOARD",
    "title": "CONTINUOUS ASSESSMENT OBSERVATION CHECKLIST FOR THE PROJECT",
    "instructions_title": "Instructions to the facilitator.",
    "instructions": [
        "This observation checklist contains four competencies which must be assessed from S.3 to S.4.",
        "The period of assessment for each competency is as follows;",
        "Please Tick against the indicator(s) the learner has exhibited at every competence assessed.",
        "Record the Number of Indicators Observed in the box provided at the end of each competence.",
        "Indicate NA if the learner has not been assessed for a particular competence(s)",
    ],
    "assessment_period_rows": [
        {
            "sn": "1",
            "competency": "Project Planning",
            "period": "S.3 Term 1 to Term 2",
            "submission": "By the last week of 2nd Term holiday of S.3",
        },
        {
            "sn": "2",
            "competency": "Project Implementation",
            "period": "S.3 Term 3 to S.4 Term 1",
            "submission": "By the last week of 1st Term holiday of S.4",
        },
        {
            "sn": "3",
            "competency": "Project Reporting",
            "period": "S.4 Term 1",
            "submission": "By the last week of 1st Term holiday of S.4",
        },
        {
            "sn": "4",
            "competency": "Project Dissemination",
            "period": "S.4 Term 1",
            "submission": "By the last week of 1st Term holiday of S.4",
        },
    ],
}

CHECKLIST_COMPETENCY_HEADINGS = {
    "Project planning": "COMPETENCY 1: PROJECT PLANNING",
    "Project implementation": "COMPETENCY 2: PROJECT IMPLEMENTATION",
    "Project reporting": "COMPETENCY 3: PROJECT REPORTING",
    "Project dissemination": "COMPETENCY 4: PROJECT DISSEMINATION",
}

PLANNING_SUBJECTS_2025 = [
    "English Language",
    "Literature in English",
    "CRE",
    "IRE",
    "History and Political Education",
    "Geography",
    "Ugandan Sign Language",
    "Chinese",
    "Arabic",
    "Latin",
    "Local Languages",
    "Foreign Languages",
    "Mathematics",
    "Physics",
    "Chemistry",
    "Biology",
    "General Science",
    "Performing Arts",
    "Entrepreneurship",
    "Technology and Design",
    "Nutrition and Food Technology",
    "Physical Education",
    "ICT",
    "Agriculture",
    "Art and Design",
]

_GENERIC_SKILLS_ITEMS: list[ObsItem] = [
    ("i) Critical thinking and problem solving", HEADER_MAX_RATING),
    "Plans and carries out investigations.",
    "sort and analyze information.",
    "Identifies problems and ways forward.",
    "Predicts outcomes and make reasoned decisions.",
    "Evaluates different solutions.",
    ("ii) Communication", HEADER_MAX_RATING),
    "Listens attentively and with comprehension.",
    "Talks confidently and explain ideas/opinions clearly.",
    "Reads accurately and fluently.",
    "Writes and presents coherently.",
    "Uses a range of media to communicate ideas.",
    ("iii) Creativity and innovation", HEADER_MAX_RATING),
    "Uses imaginations to explore possibilities.",
    "Works with others to generate ideas.",
    "Suggests and develops new solutions",
    "Tries out innovative alternatives.",
    "Looks for patterns and makes generalizations.",
    ("iv) Mathematical computation and ICT proficiency", HEADER_MAX_RATING),
    "Uses numbers and measurements accurately.",
    "Interprets and interrogate mathematical data.",
    "Uses mathematics to justify and support decisions.",
    "Uses technology to create, manipulate and process information.",
    "Uses technology to collaborate, communicate and refine their work.",
    ("v) Cooperation and self-directed learning", HEADER_MAX_RATING),
    "Work effectively in diverse teams.",
    "Interact effectively with others.",
    "Takes responsibility for your own learning.",
    "Works independently with persistence",
    "Manages goals and time",
]

STRUCTURED_CHECKLIST: list[tuple[str, str, str, str, list[ObsItem]]] = [
    (
        "Project planning",
        "1.1",
        "Identifies a project",
        "The learner identifies the project that reflects the problem the project intends to solve through;",
        [
            "Reviewing literature",
            "Consulting peers/teachers/ other internal school community members",
            "Consulting external community members with knowledge, experience or interest in the project to be undertaken.",
        ],
    ),
    (
        "Project planning",
        "1.2",
        "Develops a project Title",
        "The learner develops a project title that;",
        [
            "is related to the theme.",
            "has the acceptable number of words 7-25.",
        ],
    ),
    (
        "Project planning",
        "1.3",
        "Establishes the purpose of the project",
        "The learner establishes the purpose of the project which reflects;",
        [
            "the goal or aim the project intends to achieve.",
            "a purpose which reflects the title and the theme.",
        ],
    ),
    (
        "Project planning",
        "1.4",
        "Develops project objectives",
        "The learner develops project objectives that are;",
        [
            "Specific",
            "Measurable",
            "Achievable",
            "Realistic and",
            "Time bound",
            "objectives that are linked to the purpose/title/theme",
        ],
    ),
    (
        "Project planning",
        "1.5",
        "Justifies the project",
        "The learner explains the reason for carrying out the project / the benefits/positive impact the project, which is relevant to;",
        [
            "the theme.",
            "the title.",
            "the purpose",
        ],
    ),
    (
        "Project planning",
        "1.6",
        "Identifies resources for the project",
        "The learner identifies resources needed to carry out the project, He/she;",
        [
            "Lists/identifies the resources required",
            "Provides justification for the resources identified",
        ],
    ),
    (
        "Project planning",
        "1.7",
        "Develops a project activity/plan",
        "The learner develops a project activity/plan for carrying out the project. It should include;",
        [
            "Relevant Project activities.",
            "Logically sequenced activities.",
            "Clear timelines.",
            "Costs for the activities.",
            "Responsible persons for carrying out the activities",
        ],
    ),
    (
        "Project planning",
        "1.8",
        "Integrates knowledge and skills of different subject disciplines",
        "The learner integrates knowledge and skills from different subject disciplines;",
        list(PLANNING_SUBJECTS_2025),
    ),
    (
        "Project planning",
        "1.9",
        "Incorporates cross cutting issues",
        "The learner incorporates different cross cutting issues in the project planning process;",
        [
            "Environmental awareness",
            "Health awareness",
            "Mixed abilities and involvement",
            "Socio-economic issues",
            "Citizenship and Patriotism",
        ],
    ),
    (
        "Project planning",
        "1.10",
        "Demonstrates generic skills in the project planning process",
        "The learner demonstrates generic skills in the project planning process and;",
        list(_GENERIC_SKILLS_ITEMS),
    ),
    (
        "Project implementation",
        "2.1",
        "Gathers resources for the project",
        "The learner Gathers resources for the project through;",
        [
            "Borrowing",
            "Exchange of materials",
            "Buying resources",
            "Improvising",
            "Fundraising for materials",
        ],
    ),
    (
        "Project implementation",
        "2.2",
        "Uses the gathered resources",
        "The learner uses the gathered resources for;",
        [
            "The planned purpose",
            "Multiple purposes",
        ],
    ),
    (
        "Project implementation",
        "2.3",
        "Engages stakeholders",
        "The Learner engages the stakeholders to play their role. He/she provides evidence of stakeholder engagement in any of the following forms;",
        [
            "Letters on the engagement (letters of invitation, request contracts, acceptance, approval etc.",
            "Reports",
            "Minutes",
            "Pictures",
            "Posters",
            "Audio and audio-visual recordings etc.",
        ],
    ),
    (
        "Project implementation",
        "2.4",
        "Creates a product/service",
        "The learner creates a product or service that;",
        [
            "is in line with the stated objectives.",
            "is authentic (learners own original work).",
            "Unique (exceptional, extra ordinary).",
        ],
    ),
    (
        "Project implementation",
        "2.5",
        "Demonstrates generic skills in the project planning process",
        "The learner demonstrates generic skills in the project planning process;",
        list(_GENERIC_SKILLS_ITEMS),
    ),
    (
        "Project reporting",
        "3.1",
        "Uses an appropriate report format",
        "The learner uses an appropriate format to generate a project report with the following aspects;",
        [
            "Title",
            "Introduction",
            "Body",
            "Conclusion",
        ],
    ),
    (
        "Project reporting",
        "3.2.1",
        "Develops content of the project report for the introduction",
        "The learner develops content for the introduction as follows;",
        [
            "Name of the project",
            "Objectives",
            "Purpose of the project.",
            "Justification of the project",
        ],
    ),
    (
        "Project reporting",
        "3.2.2",
        "Develops content of the project report for the body",
        "The learner develops content for the body as follows;",
        [
            "Activities undertaken to carry out the project",
            "Achievements.",
            "Resources mobilized.",
            "Problems/challenges faced while carrying out the project",
            "How the problems/challenges faced were handled.",
            "Lessons or skills learnt while carrying out the project",
        ],
    ),
    (
        "Project reporting",
        "3.2.3",
        "Develops content of the project report for the conclusion",
        "The Learner presents content for the conclusion as follows;",
        [
            "An overall evaluation/assessment of the project.",
            "Recommendations related to the project.",
        ],
    ),
    (
        "Project reporting",
        "3.3",
        "Uses appropriate language in the project report",
        "The learner's uses appropriate language in the project report as follows;",
        [
            "At least 5 terminologies related to the project",
            "Has less than 5 spelling errors",
            "Has less than 5 punctuation errors",
            "Has less than 5 tense errors",
        ],
    ),
    (
        "Project reporting",
        "3.4",
        "Keeps project records",
        "The learner keeps the following project records;",
        [
            "project plan",
            "budget",
            "activity schedule",
            "stakeholder engagement documents (letters, attendance lists, reports, pictures, recordings, minutes etc.)",
            "Facilitator/learner interaction records",
            "project report",
        ],
    ),
    (
        "Project dissemination",
        "4.1",
        "Disseminates the project through speaking or signing",
        "The learner orally / through signing disseminates the project report;",
        [
            "with logical flow of ideas",
            "using appropriate tense / timelines",
            "using terminologies related to the project",
            "using the aspects of voice /nonverbal cues /signs",
            "using appropriate voice projection /signs (speed and thickness).",
            "pronouncing words correctly/ using appropriate signs.",
            "using appropriate body language.",
            "using appropriate voice/sign intonation.",
        ],
    ),
    (
        "Project dissemination",
        "4.2",
        "Publishes the project report",
        "The learner publishes the project report /findings in through;",
        [
            "School library",
            "News Papers",
            "Magazines",
            "Posters/Bill boards/Notice boards",
            "Project exhibition",
        ],
    ),
    (
        "Project dissemination",
        "4.3",
        "Demonstrates generic skills in the project planning process",
        "The learner demonstrates generic skills in the project planning process;",
        list(_GENERIC_SKILLS_ITEMS),
    ),
]
